language: python
sudo: true
virtualenv:
  system_site_packages: true
python:
  - 2.7
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
        sudo apt-get --yes install python-numpy;
        sudo apt-get --yes install python-vtk;
        sudo apt-get --yes install python-matplotlib;
    else
        sudo apt-get --yes install python3-numpy;
        sudo apt-get --yes install python3-vtk;
        sudo apt-get --yes install python3-matplotlib;
    fi
install:
  - sudo pip install pep8
  - sudo pip install nose
  - sudo pip install coveralls
script:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
        nosetests --with-doctest --with-coverage;
    else
        nosetests3 --with-doctest --with-coverage;
    fi
after_success:
    coveralls

#language: python
#python:
#  - 2.7
#  - 3.2
## run on the new Travis infrastructure
#sudo: false
#
## Install stuff
#before_install:
#  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
#      wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
#    else
#      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#    fi
#  - chmod +x miniconda.sh
#  - ./miniconda.sh -b
#  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
#      export PATH=/home/travis/miniconda2/bin:$PATH;
#    else
#      export PATH=/home/travis/miniconda3/bin:$PATH;
#    fi
#  - conda update --yes conda
#install:
#  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy matplotlib vtk
#  - pip install pep8 python-coveralls
## Run test
#script:
#  - nosetests
